//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGCP.APPMobile.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cc_publicaciones_items
    {
        public string COD_PERIODO_PUBLICACION { get; set; }
        public string COD_PUBLICACION { get; set; }
        public string COD_PUBLICACION_ITEM { get; set; }
        public string DES_ITEM_TRAMITE { get; set; }
        public decimal VLR_CANTIDAD { get; set; }
        public string DES_UNIDAD_MEDIDA { get; set; }
        public string DES_OBSERVACION { get; set; }
        public string DES_IDENTIFICACION_PLIEGO { get; set; }
        public Nullable<decimal> NUM_RENGLON { get; set; }
        public string DES_ID_TRAMITE_ITEM { get; set; }
        public decimal NUM_CONTROL_CONCURRENCIA { get; set; }
        public string COD_UNSPSC { get; set; }
    }
}
