//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGCP.APPMobile.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_TRAMITE_ITEMS
    {
        public string COD_UNIDAD_COMPRAS { get; set; }
        public string ID_TRAMITE { get; set; }
        public string ID_ITEM { get; set; }
        public string DES_ITEM_TRAMITE { get; set; }
        public decimal VLR_CANTIDAD { get; set; }
    }
}
