//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGCP.APPMobile.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionNotificacion
    {
        public int Id { get; set; }
        public int DispositivoId { get; set; }
        public int TipoCatalogoId { get; set; }
        public string CatalogoId { get; set; }
        public int EstadoId { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Dispositivo Dispositivo { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual TipoCatalogo TipoCatalogo { get; set; }
    }
}
