//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGCP.APPMobile.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MAppEntities : DbContext
    {
        public MAppEntities()
            : base("name=MAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Dispositivo> Dispositivo { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<LogTransaccion> LogTransaccion { get; set; }
        public DbSet<TipoCatalogo> TipoCatalogo { get; set; }
        public DbSet<TipoTransaccion> TipoTransaccion { get; set; }
        public DbSet<CC_DOM_ESTADOS> CC_DOM_ESTADOS { get; set; }
        public DbSet<CC_MODALIDAD_COMPRA> CC_MODALIDAD_COMPRA { get; set; }
        public DbSet<CC_PUBLICACIONES> CC_PUBLICACIONES { get; set; }
        public DbSet<cc_publicaciones_items> cc_publicaciones_items { get; set; }
        public DbSet<CC_RUBROS> CC_RUBROS { get; set; }
        public DbSet<CC_TRAMITE_ITEMS> CC_TRAMITE_ITEMS { get; set; }
        public DbSet<CC_TRAMITES_COMPRAS> CC_TRAMITES_COMPRAS { get; set; }
        public DbSet<CL_CAPITULO> CL_CAPITULO { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<ConfiguracionNotificacion> ConfiguracionNotificacion { get; set; }
        public DbSet<SistemaOperativo> SistemaOperativo { get; set; }
        public DbSet<CC_UNIDAD_COMPRAS> CC_UNIDAD_COMPRAS { get; set; }
    }
}
