//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGCP.APPMobile.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoTransaccion
    {
        public TipoTransaccion()
        {
            this.LogTransaccion = new HashSet<LogTransaccion>();
        }
    
        public int Id { get; set; }
        public string TipoTransaccion1 { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<LogTransaccion> LogTransaccion { get; set; }
    }
}
