//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGCP.APPMobile.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_RUBROS
    {
        public string COD_RUBRO { get; set; }
        public string DES_RUBRO { get; set; }
        public Nullable<System.DateTime> FCH_BAJA { get; set; }
    }
}
