//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGCP.APPMobile.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_TRAMITES_COMPRAS
    {
        public string COD_UNIDAD_COMPRAS { get; set; }
        public string COD_MODALIDAD { get; set; }
        public string COD_RUBRO_PRINCIPAL { get; set; }
        public string ID_TRAMITE { get; set; }
        public string COD_PERIODO { get; set; }
        public string DES_CARATULA { get; set; }
        public string DES_TRAMITE { get; set; }
        public Nullable<System.DateTime> FCH_ESTIMADA_ADJUDICACION { get; set; }
        public string NUM_PLIEGO { get; set; }
        public string DES_CONTACTO { get; set; }
        public string DES_EMAIL_CONTACTO { get; set; }
        public Nullable<System.DateTime> FCH_INICIO { get; set; }
        public Nullable<System.DateTime> FCH_INICIO_RECEP_OFERTAS { get; set; }
        public Nullable<System.DateTime> FCH_FIN_RECEP_OFERTAS { get; set; }
        public Nullable<System.DateTime> FCH_EXT_RECEP_OFERTAS { get; set; }
        public string DES_DOMICILIO_ENTREGA_OFERTA { get; set; }
        public Nullable<System.DateTime> FCH_PRIMERA_APERTURA { get; set; }
        public string HRA_PRIMERA_APERTURA { get; set; }
        public Nullable<System.DateTime> FCH_EXT_PRIMERA_APERTURA { get; set; }
        public string HRA_EXT_PRIMERA_APERTURA { get; set; }
        public Nullable<System.DateTime> FCH_SEGUNDA_APERTURA { get; set; }
        public string HRA_SEGUNDA_APERTURA { get; set; }
        public Nullable<System.DateTime> FCH_EXT_SEGUNDA_APERTURA { get; set; }
        public string HRA_EXT_SEGUNDA_APERTURA { get; set; }
        public string DES_DOMICILIO_ACTO_APERTURA { get; set; }
        public Nullable<System.DateTime> FCH_APROBACION { get; set; }
        public string VINCULO { get; set; }
        public string COD_ESTADO { get; set; }
        public string COD_TIPO_EXCEPCION_COMPRA { get; set; }
    }
}
