//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGCP.APPMobile.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispositivo
    {
        public Dispositivo()
        {
            this.ConfiguracionNotificacion = new HashSet<ConfiguracionNotificacion>();
            this.LogTransaccion = new HashSet<LogTransaccion>();
        }
    
        public int Id { get; set; }
        public string GCMRegistroId { get; set; }
        public int EstadoId { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int SistemaOperativoId { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual ICollection<ConfiguracionNotificacion> ConfiguracionNotificacion { get; set; }
        public virtual ICollection<LogTransaccion> LogTransaccion { get; set; }
        public virtual SistemaOperativo SistemaOperativo { get; set; }
    }
}
